ui:
  ssl: false
  host: localhost
  port: 4000
  nameSpace: /

# This example is valid if your Backend is publicly available at https://api.mydspace.edu/server/
# The REST settings MUST correspond to the primary/public URL of the backend. Usually, this means they must be kept in sync
# with the value of "dspace.server.url" in the backend's local.cfg
rest:
  ssl: false
  host: localhost
  port: 8080
  nameSpace: /server

## CRIS Layout
# Configuration for CRIS Layout
crisLayout:
  itemPage:
    OrgUnit:
      orientation: horizontal
    Project:
      orientation: horizontal
    default:
      orientation: horizontal
